# Generated by Django 5.1.7 on 2025-04-10 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='surname',
        ),
    ]
