# Generated by Django 5.1.7 on 2025-04-22 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0006_alter_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessiontopic',
            name='agree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='disagree',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='neutral',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
