# Generated by Django 5.1.7 on 2025-04-23 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0007_alter_sessiontopic_agree_alter_sessiontopic_disagree_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OkrugModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('okrug_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='okrugId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='a1.okrugmodel'),
        ),
    ]
