# Generated by Django 5.1.7 on 2025-04-24 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0008_okrugmodel_profile_okrugid'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizesession',
            name='passed',
            field=models.BooleanField(default=False),
        ),
    ]
