# Generated by Django 5.1.7 on 2025-04-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0010_organizesession_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sessiontopic',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
