# Generated by Django 5.1.7 on 2025-04-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a1', '0011_sessiontopic_done'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organizesession',
            name='council_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='agree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='disagree',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sessiontopic',
            name='neutral',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
